<?php
$array = $this->viewData;
?>

<table border="1" style="text-align: center; margin-bottom: 30px">

    <?php
    foreach ($array['schools'] as $school => $students) { ?>
        <tr>
            <th><?= $school ?></th>
            <th><?= $students[0]['description'] ?></th>
            <th><?= $students[0]['outputType'] ?></th>
        </tr>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Action</th>
        </tr>
        <?php
        foreach ($students as $student) { ?>
            <tr>
                <td><?= $student['id'] ?></td>
                <td><?= $student['name'] ?></td>
                <td><a href="/?student=<?= $student['id'] ?>">View <?= $student['outputType'] ?></a></td>
            </tr>
        <?php
        }
    }
    ?>

</table>

<h3>Add School</h3>
<form name="addSchool" action="/addSchool" method="post">
    <label for="school_name">School name</label>
    <input type="text" id="school_name" name="school_name"><br>
    <label for="grading_type">Grading type</label>
    <select id="grading_type" name="grading_type">
        <?php
        foreach ($array['gradigTypes'] as $gradingType) { ?>
            <option value="<?= $gradingType['id'] ?>"><?= $gradingType['type'] ?></option>
        <?php
        }
        ?>
    </select><br>
    <label for="output_type">Output type</label>
    <select id="output_type" name="output_type">
        <?php
        foreach ($array['outputTypes'] as $outputType) { ?>
            <option value="<?= $outputType['id'] ?>"><?= $outputType['type'] ?></option>
        <?php
        }
        ?>
    </select><br>
    <input type="submit" value="Add School">
</form>
